version: "3"
services:
  app:
    container_name: big-dipper-desmos
    ports:
      - 3000:3000
    build: .
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    env_file:
      - .env
