name: Test
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run lint check
      run: npm run lint
  Unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      run: npm install --save https://github.com/forbole/big-dipper-internal-ui/tarball/master
    - name: Run tests
      run: npm test -- --coverage
    - name: Upload coverage 📤
      uses: codecov/codecov-action@v1
      with:
        file: coverage/lcov.info
        fail_ci_if_error: true
  Build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run build check
      run: npm run build
