name: Test
on: push
jobs:
  Unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm test -- --coverage
    - name: Upload coverage 📤
      uses: codecov/codecov-action@v1
      with:
        file: coverage/lcov.info
        fail_ci_if_error: true
